runtime: python39
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 15
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  OPENAI_KEY: "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"

